#Configuração de rotas
/login-form:  LoginFormController
/login: LoginController
/logout:  LogoutController
/404found:  path404Controller
/main: MainController
/gerenciarAluno: GerenciarAlunoController
/gerenciarProfessor: GerenciarProfessorController
/gerenciarAdmin: GerenciarAdminController
/gerenciarTurma: GerenciarTurmaController
/cadastrarAdmin: CadastrarAdminController
/adicionarUsuario: AdicionarAdmController
/formValidaUser: FormValidaUserController
/validaUser: ValidaUserController