#Configuração de rotas
/login-form:  LoginFormController
/login: LoginController
/logout:  LogoutController
/404found:  path404Controller
/main: MainController
/gerenciarAluno: GerenciarAlunoController
/gerenciarProfessor: GerenciarProfessorController
/gerenciarAdmin: GerenciarAdminController
/adicionarUsuario: AdicionarAdmController
/validaUser: ValidaUserController