#Configuração de rotas
/login-form:  LoginFormController
/login: LoginController
/logout:  LogoutController
/404found:  path404Controller
/main: MainController

/storeUsuario: StoreUsuarioController
/editarUsuario: EditarUsuarioFormController
/deletarUsuario: DeletarUsuarioController
/inativarUsuario: InativarUsuarioController

/formValidaUser: FormValidaUserController
/validaUser: ValidaUserController

/gerenciarAdmin: GerenciarAdminController
/cadastrarAdmin: CadastrarAdminController

/gerenciarProfessor: GerenciarProfessorController
/cadastrarProfessor: CadastrarProfessorController

/gerenciarAluno: GerenciarAlunoController
/cadastrarAluno: CadastrarAlunoController

/gerenciarTurma: GerenciarTurmaController
/cadastrarTurma: CadastrarTurmaController
/editarTurma: EditarTurmaFormController
/turmaManager: TurmaManagerController
/storeTurma: StoreTurmaController
/minhaTurma: MinhaTurmaController

/cadastrarDisciplina : CadastrarDisciplinaController
/storeDisciplina: StoreDisciplinaController
/editarDisciplina: EditarDisciplinaFormController
/historicoDisciplina: HistoricoDisciplinaController
/minhasDisciplinas: MinhasDisciplinasController
/finalizarDisciplinaForm: FinalizarDisciplinaFormController
/finalizarDisciplina: FinalizarDisciplinaController

/solicitarMatricula: SolicitarMatriculaController
/cancelarMatricula: CancelarMatriculaController


